all:
	gcc Ordenacao.h Ordenacao.c Random.h Random.c Soma.h Soma.c buscaBinaria.c -o exec
production:
	gcc Ordenacao.h Ordenacao.c Random.h Random.c Soma.h Soma.c buscaBinaria.c -o exec
clean:
	rm exec
run:
	./exec
